# Generated by Django 3.2.8 on 2022-04-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True, verbose_name='frecuencia'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='item',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(max_length=100, null=True, verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='staus',
            field=models.CharField(max_length=100, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicación',
            field=models.CharField(max_length=100, null=True, verbose_name='ubicacion'),
        ),
    ]
