# Generated by Django 3.2.8 on 2022-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20220407_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='staus',
        ),
        migrations.AddField(
            model_name='equipo',
            name='estatus',
            field=models.CharField(max_length=100, null=True, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='funcion',
            field=models.TextField(null=True, verbose_name='Función del Equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
