# Generated by Django 3.2.8 on 2022-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20220408_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='id',
            new_name='clave',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='item',
        ),
        migrations.AddField(
            model_name='equipo',
            name='dominio',
            field=models.CharField(max_length=100, null=True, verbose_name='Dominio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ficha_mantenimiento',
            field=models.CharField(max_length=100, null=True, verbose_name='Ficha de mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='num_serie',
            field=models.CharField(max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicación',
            field=models.CharField(max_length=100, null=True, verbose_name='ubicación'),
        ),
    ]
