# Generated by Django 3.2.8 on 2022-04-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20220417_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='clave',
            new_name='id',
        ),
    ]
