# Generated by Django 3.2.8 on 2022-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_equipo_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
