# Generated by Django 3.2.8 on 2022-04-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_equipo_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_ingreso',
        ),
    ]
