# Generated by Django 3.2.8 on 2022-04-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_auto_20220417_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_hora',
        ),
    ]
