# Generated by Django 3.2.8 on 2022-04-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_alter_equipo_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True, verbose_name='frecuencia'),
        ),
    ]
