# Generated by Django 3.2.8 on 2022-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_remove_equipo_frecuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True, verbose_name='frecuencia'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ficha_mantenimiento',
            field=models.CharField(max_length=100, null=True, verbose_name='Ficha de mantenimiento'),
        ),
    ]
