# Generated by Django 3.2.8 on 2022-04-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20220417_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia',
        ),
    ]
