# Generated by Django 3.2.8 on 2022-04-17 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_remove_equipo_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True, verbose_name='frecuencia'),
        ),
    ]
