# Generated by Django 3.2.8 on 2022-04-19 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_remove_equipo_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
                ('responsable', models.CharField(max_length=100, null=True, verbose_name='Responsable')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.equipo')),
            ],
        ),
    ]
