# Generated by Django 3.2.8 on 2022-04-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0025_auto_20220419_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='equipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
