# Generated by Django 3.2.8 on 2022-04-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0028_alter_mantenimiento_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='equipo',
        ),
    ]
