# Generated by Django 3.2.8 on 2022-04-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0029_remove_mantenimiento_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='equipo_mantenimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.equipo'),
        ),
    ]
