# Generated by Django 3.2.8 on 2022-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0030_mantenimiento_equipo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=100, null=True, verbose_name='QR')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
