# Generated by Django 3.2.8 on 2022-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0031_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr',
            field=models.URLField(null=True, verbose_name='QR'),
        ),
    ]
