# Generated by Django 3.2.8 on 2022-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0032_alter_qrcode_qr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qrcode',
        ),
        migrations.AddField(
            model_name='equipo',
            name='qr',
            field=models.URLField(null=True, verbose_name='QR'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
