# Generated by Django 4.0.3 on 2022-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0034_alter_equipo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='qr_code',
        ),
    ]
