# Generated by Django 4.0.3 on 2022-04-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0035_qrcode_remove_equipo_qr_remove_equipo_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='equipo_mantenimiento',
        ),
        migrations.AddField(
            model_name='equipo',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
