# Generated by Django 4.0.3 on 2022-04-20 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0036_remove_mantenimiento_equipo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 4, 20, 22, 59, 27, 599197, tzinfo=utc), verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
