# Generated by Django 4.0.3 on 2022-04-20 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0037_mantenimiento_fecha_inicio_alter_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 20, 23, 4, 34, 289689, tzinfo=utc), verbose_name='Hora'),
            preserve_default=False,
        ),
    ]
